config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  #customize resources route
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about' 

  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
  	member do
  	  get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
  root to: "pages#home"

end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot">
	<div class="inner">
	  	<p class="app-footer"><%= copyright_generator %></p>
	</div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Andrew Oliveira</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link','span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p> <%= copyright_generator %> </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <span><%= link_to 'Write a new Blog', new_blog_path if logged_in?(:site_admin) %></span>
    <span><%= link_to 'Topics', topics_path %></span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light blog-nav">
  <div class="container">
	  <%= link_to 'Andrew Oliveira', root_path, class: 'navbar-brand' %>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
	    	<%= nav_helper 'nav-link', 'li' %>
	    	<%= login_helper 'nav-link' %>
	    </ul>
	  </div>
	</div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-sm-3 ml-sm-auto blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Analista e Desenvolvedor de Sistemas pelo Instituto Federal de São Paulo. Amante da web em todos os níveis de sua Stack e entusiasta de Ruby e Clojure.</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>

  <div class="sidebar-module">
    <h4> Topics </h4>
    <% @side_bar_topics.each do |topic|%>
      <p><%= link_to topic.title, topic_path(topic)%> </p>
    <%end%>
  </div>
  <div class="sidebar-module text-center">
    <ol class="list-unstyled social-links">
      <li>
        <a href="https://github.com/andrewhenriquef"><%= fa_icon "github"%></a>
        <a href="https://twitter.com/andrewhenriquef"><%= fa_icon "twitter"%></a>
        <a href="https://www.linkedin.com/in/andrew-oliveira-52184870/"><%= fa_icon "linkedin"%></a>
      </li>
      <li>
        <a href="https://www.facebook.com/andrewhenriquef"><%= fa_icon "facebook"%></a>
        <a href="https://www.instagram.com/andrewhenriquef/"><%= fa_icon "instagram"%></a>
      </li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to 'Home', root_path%></div>
  <div><%= link_to 'About me', about_me_path%></div>
  <div><%= link_to 'contact', contact_path%></div>
  <div><%= link_to 'Blogs', blogs_path%></div>
  <div><%= link_to 'Portifolio', portfolios_path%></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      
  	  <%= link_to 'View all portfolio items', portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p> <%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My portfolio</h1>
    
    <p class="lead text-muted">
      Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.
    </p>
    
    <p>
      <%= link_to 'Find out more about me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        
        <div class="col-sm-8 py-4">
          <h4 class="text-white">About</h4>
          
          <p class="text-muted">
            We work together to create a better world. We are building software for analyses and to improve humans life.
            <br>
            We create solutions for your business.
          </p>
        </div>
        
        <div class="col-sm-4 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">

            <%= nav_helper 'text-white','li' %>
            <li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      
      </div>
    </div>
  </div>

  <div class="navbar navbar-dark bg-dark">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand">Andrew Oliveira</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>


</header>